### PR TITLE
Overview of the components in the sample solution

### PR DESCRIPTION
**Pull request by bennage**
I extracted this branch from #64, so that we can have an indepdent discussion. There's a lot to talk about here and I don't want it to hold up the work there.
Expect some feedback here shortly.
//cc @JohnPWSharp
connects to #99

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bennage__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (christb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bennage** [comment]
I think we should wait on this as it is affected by the work in #117.

**Comment by hveiras** [comment]
@bennage  @JohnPWSharp  work made in #86 will also affect the content of Warm Storage. Otherwise the content in this PR reflects well the current status on master IMO.

**Comment by bennage** [comment]
@JohnPWSharp Did you mean to close this without merging into master?

**Comment by JohnPWSharp** [comment]
I did. It has been superseded by #135

**Comment by bennage** [comment]
Thanks

**Pull request closed without merging**
