### PR TITLE
Structure the repo to support multiple implementations

### PR DESCRIPTION
**Pull request by hveiras**
-Splited solution into separate folders by scenario.
-Refactored provisioning scripts to allow deployment by individual scenario.

connects to #147

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hveiras__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by hveiras** [comment]
AppVeyor build is failing because it is still looking for the root solution which no longer exists on this structure.

**Comment by lbrader** [comment]
In reviewing the goals for this PR, which is to break it up in terms of scenario's based on technology implementation. 

Here are the issues I'm having on the general re-structuring:

Bugs

*Provision-ColdStorageEventProcessor.ps1 & Provision-WarmStorageEventProcessor.ps1 failed due to the following:
** Bug: failed on New-AzureSBNameSpace entry. "The specified service namespace is not available."
** Never asked me for ServiceBus Name Space.. It set to false and uses a default name, which fails. 
** Bug: a # of Null-value expression in creating a consumer group, endpoints 
** Bug: Simulator.EventHubSasPrimaryKey couldn't be found
** They both write to the various <>.config files, but they are corrupted with the values.  

*Provision in general - potential bug source
** Question: Why are we using defaults? vs.  requesting as before?
** We are asking for a storage account that could be in a completely different region.  Yet we are defaulting the ServiceBus  to "Central US".  This will also add additional cost.
** Warm-configuration is missing LogLevel setting
** Cold-configuration is missing LogLevel setting

*Provision-ColdStorageAzureSTreamAnalytics.ps1
** Bugs: There are several bugs here. Starting with gathering only partial amount of data. For examples ask for the SQL password, but not a corresponding SQL.  

*Provision-ColdStorageHDInsight.ps1
** Bug handling : Unable to create cluster - insufficient resource cores available.  
** Bug: Message at the end "Provision Finished OK".  It failed but still set the output to ok.

Note: After provisioning. I could compile the projects because the <>.config file exist. But the code would failed to the bad provisioning.

General Issues with the re-structuring

-I thought we would have a SLN for each technology scenario.  Instead it appears that the re-structure is to split up ColdPath and WarmPath scenario.  I really don't see any technology breakout.
-We have 2 SLN each dedidicated to only show Cold or a Warm path scenario.  Is this how we want to present the material?  


Specific Issues with the re-structuring
* Repetitive naming with "EventProcessor".  
** For example, src\WarmStorage.EventProcessor\src\WarmStorage.EventProcessor.
** It's repeated over in the SLN names 

* Under Common directory where I see DotNet, which i assume is for different technology. And this only contains the Simulator.  
** Why is there a DotNet?  What is the alternative? if we go to Linux, wouldn't we still be using dotnet ported to Linux? 
** I don't believe we are going to create a Java Simulator.  And least I don't know of any plans.

* The Simulator configuration is creation is repeated under the Cold Path provisioning and the Warm Path provisioning.
** This will cause an overhead to the user as they could have to simulator-configuration files to maintain. 
** I would rather split out the Simulator provisioning and have only 1 file to maintain. 

* Under Tests.Common
** Move ConsoleHost.cs to Core


Here's my attempt at a restructuring. Ok, I see to minimize the repetition i end up with the same Cold & Warm break out. 
note 1: i think the Simulator should be at top level.  You end up looking for it buried inside. 


src
- ColdPath
  * ColdPath.sln
   - src
     - ColdPath.EventProcessor
     - ColdPath.ConsoleHost
     - ColdPath.Storm
     - ColdPath.Test
- Common
   - Shared
      - Core
      - Core.Tests
      - Devices.Events
      - Tests.Common <don't  like this name but don't have anything better>
   - Simulator 
- Validation
- WarmPath
  * WarmPath.sln
   - src
     - WarmPath.EventProcessor
     - WarmPath.ConsoleHost

**Comment by azurecla** [comment]
Hi __@hveiras__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by bennage** [comment]
Here's how I would like to proceed. We can disregard the provisioning bugs for now, and open indepedent issues if they are still present in the final merge.
I like the decomposition of the provisioning scripts.
I agree with Larry's feedback about the restructuring. Here's what I'd like:
- build
- docs
- provision
- scenarios
  - ad-hoc exploration
  - long-term storage
  - shared
  - simulator

For each top-level under `scenarios`, let's have:
- DotNet
- Java
as appropriate.

Inside each platform folder, let's follow the conventions for that platform. In the case of `DotNet`, I would like to remove the `src` and `tests` and just have all of the individual project folders there (and the .sln file for the scenario).

I like the use of the `nuget.config` files for sharing common packages.

**Comment by bennage** [comment]
Also, we **do not** need the `.nuget` folders.  This is an old approach that is no longer necessary. I don't want to introduce the binary nuget.exe to our repo.

**Comment by bennage** [comment]
Here's a link about migrating away form the .nuget folders: https://docs.nuget.org/Consume/Package-Restore/Migrating-to-Automatic-Package-Restore

**Comment by bennage** [comment]
This is replaced by #213.

**Pull request closed without merging**
