### PR TITLE
pointed to wrong directory - now pointing to pnp-iotjourney

### PR DESCRIPTION
**Pull request by lbrader**
connect to #258 

Simple issue.  We are using 'pnp-iotjourney' as our directory name.  Not
'fabrikdam'

### CODE REVIEW

**Comment by hveiras** [comment]
@lbrader  I see that the StreamAnalyticsJobDefinitionColdStorage.json is using "BlobPathPrefix": "fabrikam" in it's output definition, I think changing the directory name only on the query will broke it. Can you change it there as well and test? what was the renaming for? thanks.

**Comment by francischeung** [comment]
I updated the folder to be consistent with the Stream Analytics job. The .NET Event Processor should be sending data to the the "Fabrikam" folder.

**Comment by hveiras** [comment]
@francischeung  so, should we keep 'Fabrikam' in this query?

**Comment by francischeung** [comment]
Absolutely.

**Pull request closed without merging**
