### PR TITLE
fixes static analysis issues.

### PR DESCRIPTION
**Pull request by francischeung**
Connects to #243

### CODE REVIEW

**Comment by bennage** [comment]
Were you expecting this to pass or fail in CI?

**Comment by francischeung** [comment]
This first test should pass. I just added the internal ruleset to a project. Next commit will force code analysis on build.

**Comment by francischeung** [comment]
I've updated the projects in the ScenarioSimulator solution to use the custom ruleset file. The other 3 solutions need to be updated.

IotJourney.ruleset: CA1305 is a "Warning". If you change it to "Error", the build will break, as expected.

**Comment by bennage** [comment]
Hmm... I suspect that you'll need a NuGet package to trigger the build task. Some options are:
- http://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/
- http://www.nuget.org/packages/BuildTools.FxCop/

I'm particularly curious about the Rosyln one.

**Pull request merged**
