### PR TITLE
Added Semantic Log Event for Current Events Per Second

### PR DESCRIPTION
**Pull request by lbrader**
connects to #176 

This adds a new semantic log event that captures the current through in
terms of events per second.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lbrader__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (lbrader). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by francischeung** [comment]
Looks good. Just waiting for #147 to get merged.

**Comment by lbrader** [comment]
In our analysis #30 we have found a way to get more accurate.   I have added a stopwatch to calculate our rate allowing for better accuracy.

**Comment by bennage** [comment]
I have a slight improvement I'd like to make here. I'll push it up shortly.

**Comment by bennage** [comment]
Ok, I've made my changes. Please review.

**Pull request merged**
