### PR TITLE
Provision HDInsight instance

### PR DESCRIPTION
**Pull request by hveiras**
- Provisioning of HDInsight cluster.
- Removed unnecessary defaults.

connects to #53
connects to #65 
connects to #58

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hveiras__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by lbrader** [comment]
Reviewing Pull Request - running through provisioning scripts

**Comment by lbrader** [comment]
@hveiras Following issues
[ ] a error is thrown when their is already an existing HD Cluster.  Need to check for existing cluster
[ ] need to add a message on the creation of a cluster.  It took over 10 minutes

**Comment by hveiras** [comment]
@lbrader Thanks for the feedback. I made the changes.

**Comment by francischeung** [comment]
Closing this PR since PR #74 is the superset of these commits.

**Pull request closed without merging**
