### PR TITLE
Added directory (fabrikam) to path for external table

### PR DESCRIPTION
**Pull request by JohnPWSharp**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@JohnPWSharp__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by JohnPWSharp** [comment]
@bennage @lbrader @hanzzhang Hopefully this now works as expected - the directory (fabrikam) was missing from the path in the CREATE EXTERNAL TABLE statement. I now get a list of events and counts on stdout

**Comment by bennage** [comment]
@JohnPWSharp you need to update your master branch and rebase this pull request before we can merge it.

**Comment by JohnPWSharp** [comment]
Closed - it will be simpler to recreate this PR from my updated master

**Pull request closed without merging**
