### PR TITLE
[do not merge] exploring the simulator problem

### PR DESCRIPTION
**Pull request by bennage**
This is with respect to #161.

I can get good results with

``` xml
  <add key="Simulator.NumberOfDevices"
       value="2000"/>
  <add key="Simulator.SenderCountPerInstance"
       value="600"/>
```

However, if I up the `Simulator.NumberOfDevices` to **3,000** then I max out my CPU. 
Interestingly, if I replace [this line](https://github.com/mspnp/iot-journey/blob/bennage/simulator/src/Implementation/Simulator/ScenarioSimulator/EventSender.cs#L44)

``` C#
await this._eventHubClient.SendAsync(eventData).ConfigureAwait(false);
```

with this

``` C#
await Task.Delay(0).ConfigureAwait(false);
```

Then the CPU drops below 50%, and I average the expected 3,000 events per sec.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bennage__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (christb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bennage** [comment]
Also, when `Simulator.NumberOfDevices` is 2,000,
If I play with the value of `Simulator.SenderCountPerInstance`, a value of:

    1 -> ~1,500 events/sec
    2 -> ~2,000 events/sec

This makes me think that we don't need a lot messaging factories. I still do not know how this affects the new logic with security tokens.

**Comment by lbrader** [comment]
#161  Did you remove the  jittery and other loopfrequency delay's?    As noted in my experiments yesterday.  I did get about 1 event/sec  .  I'm still working with low # of devices under 10 but with a single message factory.  The jittery was adding a 25% delay in our messaging.

**Comment by lbrader** [comment]
Reviewed the PR and this looks all good.  The jittery now looks good.   Just for other information, the jittery is added to ensure we are pounding the IO and add some randomness.   Me, i think we are getting enough jittery in most cases from other associated call.

But, it's far better to have this logic - as all machines not being equal.

Waiting on the provisioning to be completed before added. #157 PR

**Comment by bennage** [comment]
We've documented the learnings here in #161.

**Pull request closed without merging**
